### ISSUE TITLE
Show the correct help menu

### ISSUE THREAD

**Issue by fabiocontiero** [fireworkweb/fwd#44]
When it runs a command with --help option in a command with sub commands, is showed the help menu for the first command.
![image](https://user-images.githubusercontent.com/11239101/57229788-51b10a00-6fed-11e9-81eb-d0aff5cd1e09.png)

**Comment by fabriciojs** [comment]
This is an issue we will probably have to deal with the framework internals to solve, and the flags are getting parsed. Maybe the solution will have to be to "stringify" the input when having such conflicting flags.

`fwd yarn -v` - works
`fwd yarn --help` - works
`fwd artisan --help` - works
`fwd artisan view:clear --help` - does not work; will bring the same help for `artisan` instead of `view:clear`;
`FWD_DEBUG=1 fwd artisan view:clear --help` - does not work;  not even FWD_DEBUG will be applied in such case;

To make it work for now we have the workaround of "stringifying" the parameters so they don't match the default --help flag:

`fwd artisan "view:clear" "--help "` -> will bring the correct help. (notice the ugly space hack in the --help flag)

We need to adjust the default command `--help` flag parsing to ignore it in case it lies within any other parameters, or disable it at all to avoid conflicts (and the create a new `man` or `help` command to replace it.

**Comment by dbpolito** [comment]
This won't be simple to implement to do limitation of `Symfony/Console`, the logic that handles these features are:

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Application.php#L192-L196
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Application.php#L215-L224

While Laravel already extends from this class and could overwrite this method, we would need to duplicate the whole logic to disable these specific lines.

We would need to open a PR on `Symfony/Console` improving this logic by moving this logic to methods like: `handleHelpParam` and `handleVersionParam` so we could extend and simply disable this logic.
