### ISSUE TITLE
Read .fwd from user $HOME

### ISSUE THREAD

**Issue by gabrielboliveira** [fireworkweb/fwd#63]
It would be useful to read `.fwd` from the user $HOME, to allow customization per user workspace.

**Comment by fabriciojs** [comment]
This is a nice idea, but the precedence game becomes even harder.

Maybe something like:

1. .fwd (distributed)
2. .fwd (home) <<<<< new addition
3. .fwd (project local, versioned?)
4. .env (project local)


The problem is currently the project local .fwd has everything, which would override and make the HOME one useless.

We may:

1. Change the default local project version of .fwd to have almost everything commented out (keeping only the images to avoid possible future breaking changes).

That seems like a plan.

What you guys think? cc @dbpolito @gabrielboliveira

**Comment by gabrielboliveira** [comment]
The use case for this, as as an example, is if you choose a system with a different architecture. Eg the new Raspberry Pi 4. The default images are tagged with amd64 architecture in mind, and those don't work very well with the ARM from RPi.

So you have `.fwd` file at your `$HOME`, you could set the images to use the arm tags (to be added as well).

**Comment by fabriciojs** [comment]
This platform based issue could point us to an even better solution - `fwd` can come out of the box with different defaults for difference environments, which would also help for Windows usage as documented in https://github.com/fireworkweb/fwd/issues/42#issue-439701540.

Nevertheless the change in environment files load + the addition of the HOME one is a nice thing we will do.

**Comment by fabriciojs** [comment]
Implemented; will go in the next RC for 1.0.

A very basic and primitive documentation for this feature exists in the README.
